code --install-extension antfu.vite
code --install-extension anthonyjgatlin.vscode-cypher-query-language-tools
code --install-extension christian-kohler.npm-intellisense
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension gitlab.gitlab-workflow
code --install-extension grafana.grafana-alloy
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension gruntfuggly.todo-tree
code --install-extension gurumukhi.selected-lines-count
code --install-extension heaths.vscode-guid
code --install-extension jock.svg
code --install-extension jozefchmelar.compare
code --install-extension lextudio.restructuredtext
code --install-extension mechatroner.rainbow-csv
code --install-extension meezilla.json
code --install-extension michakaleta.folderformatter
code --install-extension mikestead.dotenv
code --install-extension moshfeu.compare-folders
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.flake8
code --install-extension ms-python.isort
code --install-extension ms-python.mypy-type-checker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.js-debug
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ryu1kn.partial-diff
code --install-extension ryuta46.multi-command
code --install-extension samuelcolvin.jinjahtml
code --install-extension seanwu.vscode-qt-for-python
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension the-compiler.python-tox
code --install-extension trond-snekvik.simple-rst
code --install-extension twxs.cmake
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension william-voyek.vscode-nginx
